"""Unofficial Python SDK for the Tally.so API."""

from tally.client import TallyClient
from tally.exceptions import (
    BadRequestError,
    ForbiddenError,
    NotFoundError,
    RateLimitError,
    ServerError,
    TallyAPIError,
    TallyConnectionError,
    TallyError,
    TallyTimeoutError,
    UnauthorizedError,
)
from tally.models import (
    # Enums
    BlockType,
    FormStatus,
    SubscriptionPlan,
    WebhookDeliveryStatus,
    WebhookEventType,
    # Core Models
    Form,
    FormBlock,
    FormCreated,
    FormPayment,
    FormSettings,
    Invite,
    PaginatedForms,
    PaginatedWebhookEvents,
    PaginatedWebhooks,
    PaginatedWorkspaces,
    User,
    Webhook,
    WebhookCreated,
    WebhookEvent,
    WebhookHeader,
    Workspace,
    WorkspaceInvite,
    # Payload Types (for type-safe form creation)
    BasePayload,
    BlockPayload,
    CalculatedFieldsPayload,
    CaptchaPayload,
    ConditionalLogicPayload,
    DividerPayload,
    EmbedAudioPayload,
    EmbedPayload,
    EmbedVideoPayload,
    FileUploadPayload,
    FormTitlePayload,
    Heading1Payload,
    Heading2Payload,
    Heading3Payload,
    HiddenFieldsPayload,
    ImagePayload,
    InputDatePayload,
    InputEmailPayload,
    InputLinkPayload,
    InputNumberPayload,
    InputPhoneNumberPayload,
    InputTextPayload,
    InputTimePayload,
    LabelPayload,
    LinearScalePayload,
    MatrixColumnPayload,
    MatrixPayload,
    MatrixRowPayload,
    OptionPayload,
    PageBreakPayload,
    PaymentPayload,
    QuestionPayload,
    RatingPayload,
    RespondentCountryPayload,
    SignaturePayload,
    TextareaPayload,
    TextPayload,
    ThankYouPagePayload,
    TitlePayload,
    WalletConnectPayload,
)
from tally.resources import (
    FormsResource,
    OrganizationsResource,
    UsersResource,
    WebhooksResource,
    WorkspacesResource,
)

__version__ = "0.1.0"

# Alias for convenience
Tally = TallyClient

__all__ = [
    # Main client
    "Tally",
    "TallyClient",
    # Resources
    "FormsResource",
    "OrganizationsResource",
    "UsersResource",
    "WebhooksResource",
    "WorkspacesResource",
    # Enums
    "BlockType",
    "FormStatus",
    "SubscriptionPlan",
    "WebhookDeliveryStatus",
    "WebhookEventType",
    # Core Models
    "Form",
    "FormBlock",
    "FormCreated",
    "FormPayment",
    "FormSettings",
    "Invite",
    "PaginatedForms",
    "PaginatedWebhookEvents",
    "PaginatedWebhooks",
    "PaginatedWorkspaces",
    "User",
    "Webhook",
    "WebhookCreated",
    "WebhookEvent",
    "WebhookHeader",
    "Workspace",
    "WorkspaceInvite",
    # Payload Types
    "BasePayload",
    "BlockPayload",
    "CalculatedFieldsPayload",
    "CaptchaPayload",
    "ConditionalLogicPayload",
    "DividerPayload",
    "EmbedAudioPayload",
    "EmbedPayload",
    "EmbedVideoPayload",
    "FileUploadPayload",
    "FormTitlePayload",
    "Heading1Payload",
    "Heading2Payload",
    "Heading3Payload",
    "HiddenFieldsPayload",
    "ImagePayload",
    "InputDatePayload",
    "InputEmailPayload",
    "InputLinkPayload",
    "InputNumberPayload",
    "InputPhoneNumberPayload",
    "InputTextPayload",
    "InputTimePayload",
    "LabelPayload",
    "LinearScalePayload",
    "MatrixColumnPayload",
    "MatrixPayload",
    "MatrixRowPayload",
    "OptionPayload",
    "PageBreakPayload",
    "PaymentPayload",
    "QuestionPayload",
    "RatingPayload",
    "RespondentCountryPayload",
    "SignaturePayload",
    "TextareaPayload",
    "TextPayload",
    "ThankYouPagePayload",
    "TitlePayload",
    "WalletConnectPayload",
    # Exceptions
    "TallyError",
    "TallyAPIError",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    "TallyConnectionError",
    "TallyTimeoutError",
]
